In [ ]:
#numpy: https://docs.scipy.org/doc/numpy/user/quickstart.html

In [1]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape #dimensions of the array

(3, 5)

In [6]:
a.ndim #number of dimensions

2

In [7]:
a.dtype.name

'int32'

In [8]:
a.itemsize #size in bytes of each element of the array

4

In [9]:
a.size #total number of elements of the array

15

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([6,7,8]) #array creation

In [12]:
b

array([6, 7, 8])

In [13]:
type(b)

numpy.ndarray

In [14]:
c = np.array([(1.5,2,3),(4,5,6)])

In [15]:
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((2,3,4),dtype=np.int16) #dtype is specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [18]:
np.empty((2,3)) #unitialized

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [20]:
np.arange(10,30,5) #start, stop, step

array([10, 15, 20, 25])

In [21]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [22]:
from numpy import pi

In [23]:
np.linspace(0,2,9) #9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
x = np.linspace(0,2*pi,100)

In [25]:
f = np.sin(x)

In [26]:
##Basic Operations

In [27]:
a = np.array([20,30,40,50])

In [31]:
b = np.arange(4)

In [32]:
b

array([0, 1, 2, 3])

In [33]:
c = a-b

In [34]:
c

array([20, 29, 38, 47])

In [35]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [36]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [37]:
a<35

array([ True,  True, False, False])

In [38]:
#matrix
A = np.array([[1,1],
            [0,1]])
B = np.array([[2,0],
             [3,4]])

In [39]:
A * B #elementwise poduct

array([[2, 0],
       [0, 4]])

In [40]:
A @ B #matrix product

array([[5, 4],
       [3, 4]])

In [41]:
A.dot(B) #another matrix product

array([[5, 4],
       [3, 4]])

In [45]:
a = np.random.random((2,3))

In [46]:
a

array([[0.84145426, 0.00478797, 0.71433993],
       [0.27248919, 0.48293107, 0.07998073]])

In [47]:
a.sum()

2.3959831388539303

In [48]:
a.min()

0.004787971548580572

In [51]:
a.max()

0.8414542566471546

In [53]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [55]:
b.min(axis=1)

array([0, 4, 8])

In [56]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [57]:
B=np.arange(3)
B

array([0, 1, 2])

In [58]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [59]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [60]:
C = np.array([2,-1,4])
np.add(B,C)

array([2, 0, 6])

In [61]:
#Indexing Slicing and lterating

In [62]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [63]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a[2]

8

In [65]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [66]:
a[:6:2]=-1000 # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000

In [67]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [68]:
a[::-1] #reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [69]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


C:\Users\ehezhen\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [71]:
def f(x, y):
    return 10*x+y

In [72]:
b=np.fromfunction(f,(5,4),dtype=int)

In [73]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [74]:
b[2,3]

23

In [75]:
b[0:5,1] #each row in the second colum of b

array([ 1, 11, 21, 31, 41])

In [76]:
b[:,1] #equivalent as previous 

array([ 1, 11, 21, 31, 41])

In [77]:
b[1:3, :] #each column in the second and third rwo 

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [78]:
b[-1] #the last row, equivalent to b[-1,:]

array([40, 41, 42, 43])

In [79]:
#3D array

In [80]:
c = np.array([[[0,1,2],
              [10,12,13]],
              [[100,101,102],[110,112,113]]])

In [81]:
c.shape

(2, 2, 3)

In [82]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [83]:
c[...,2], same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

In [84]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [85]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [86]:
#Shape Manipulation

In [87]:
a = np.floor(10*np.random.random((3,4)))
a

array([[6., 8., 5., 0.],
       [4., 1., 6., 9.],
       [1., 5., 7., 3.]])

In [89]:
a.shape

(3, 4)

In [90]:
a.ravel() #return the array, flattened

array([6., 8., 5., 0., 4., 1., 6., 9., 1., 5., 7., 3.])

In [91]:
a.reshape(6,2) #returns the array with a modified shape

array([[6., 8.],
       [5., 0.],
       [4., 1.],
       [6., 9.],
       [1., 5.],
       [7., 3.]])

In [92]:
a.T #return the array, transposed

array([[6., 4., 1.],
       [8., 1., 5.],
       [5., 6., 7.],
       [0., 9., 3.]])

In [93]:
a.T.shape

(4, 3)

In [94]:
#Stacking together different arrays

In [95]:
a = np.floor(10*np.random.random((2,2)))

In [96]:
a

array([[3., 1.],
       [8., 6.]])

In [97]:
b = np.floor(10*np.random.random((2,2)))

In [98]:
b

array([[6., 6.],
       [6., 7.]])

In [99]:
np.vstack((a,b))

array([[3., 1.],
       [8., 6.],
       [6., 6.],
       [6., 7.]])

In [100]:
np.hstack((a,b))

array([[3., 1., 6., 6.],
       [8., 6., 6., 7.]])

In [102]:
from numpy import newaxis
np.column_stack((a,b)) #with 2D arrays

array([[3., 1., 6., 6.],
       [8., 6., 6., 7.]])

In [103]:
a = np.array([4,2])
b = np.array([3,8])
np.column_stack((a,b)) #return a 2D array

array([[4, 3],
       [2, 8]])

In [104]:
np.hstack((a,b))

array([4, 2, 3, 8])

In [106]:
a[:,newaxis]

array([[4],
       [2]])

In [107]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4, 3],
       [2, 8]])

In [108]:
np.hstack((a[:,newaxis],b[:,newaxis])) 

array([[4, 3],
       [2, 8]])

In [109]:
a = np.floor(10*np.random.random((2,12)))
a

array([[6., 6., 4., 6., 3., 2., 7., 9., 9., 0., 9., 2.],
       [0., 4., 1., 7., 9., 4., 5., 7., 7., 6., 7., 5.]])

In [110]:
np.hsplit(a,3)

[array([[6., 6., 4., 6.],
        [0., 4., 1., 7.]]), array([[3., 2., 7., 9.],
        [9., 4., 5., 7.]]), array([[9., 0., 9., 2.],
        [7., 6., 7., 5.]])]

In [111]:
np.hsplit(a,(3,4))

[array([[6., 6., 4.],
        [0., 4., 1.]]), array([[6.],
        [7.]]), array([[3., 2., 7., 9., 9., 0., 9., 2.],
        [9., 4., 5., 7., 7., 6., 7., 5.]])]

In [112]:
#Copies and Views

In [113]:
a = np.arange(12)

In [114]:
b = a #no new object is created

In [115]:
b is a

True

In [116]:
b.shape=3,4

In [117]:
a.shape

(3, 4)

In [118]:
def f(x):
    print(id(x))

In [119]:
id(a)

87714912

In [120]:
f(a)

87714912


In [121]:
c = a.view()

In [122]:
c is a

False

In [123]:
c.base is a #c is a view of the data owned by a

True

In [124]:
c.flags.owndata

False

In [125]:
c.shape=2,6

In [126]:
a.shape

(3, 4)

In [129]:
c[0,4] = 1234 #a's data changes

In [128]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [130]:
s = a[:,1:3] #s[:] is a view of s

In [131]:
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [133]:
s[:]=10 #a will still change

In [134]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [135]:
#Deep Copy

In [136]:
d = a.copy()

In [137]:
d is a

False

In [138]:
d.base is a

False

In [139]:
d[0,0]=9999

In [140]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])